// south-vue/src/components/Results.vue
<template>
  <div>
    <div class="container mx-auto px-5 py-10">
      <div class="-m-4 flex flex-wrap">
        <Card v-for="item in items" :key="item.id" :data="item"></Card>
      </div>
    </div>
    <Pagination :pages="pages" :setCurrentPage="setCurrentPage"></Pagination>
  </div>
</template>

<script lang="ts">
import { reactive, computed, onMounted } from "vue";
import { ISearch } from "../interfaces/ISearch";
import { paginate } from "../utils/paginate";
import Card from "./Card.vue";
import Pagination from "./Pagination.vue";

export default {
  components: {
    Card,
    Pagination,
  },
  props: {
    searchQuery: String,
  },
  setup(props) {
    const state = reactive({
      currentPage: 0,
      itemsPerPage: 10,
      url: "https://www.googleapis.com/books/v1/volumes",
    });

    const fetch = computed(() => {
      return `${state.url}?q=${props.searchQuery}&startIndex=${
        state.currentPage * state.itemsPerPage
      }`;
    });

    const a: any = {};
    const { data, isLoading, error } = a;

    const items = computed(() => {
      return data?.items || [];
    });

    const totalItems = computed(() => {
      return data?.totalItems || 0;
    });

    const totalPages = computed(() => {
      return Math.ceil(totalItems.value / state.itemsPerPage);
    });

    const pages = computed(() => {
      return paginate(state.currentPage, totalPages.value);
    });

    function setCurrentPage(page: number) {
      state.currentPage = page;
    }

    return {
      isLoading,
      error,
      items,
      pages,
      setCurrentPage,
    };
  },
};
</script>

// south-react/src/components/Results.tsx
import React, { useState } from "react";
import useFetch from "../hooks/useFetch";
import { ISearch } from "../interfaces/ISearch";
import { paginate } from "../utils/paginate";
import Card from "./Card";
import Pagination from "./Pagination";

type Props = {
  searchQuery: string;
};

const Results = ({ searchQuery }: Props) => {
  const url = "https://www.googleapis.com/books/v1/volumes"; //  /s1gVAAAAYAAJ
  const [currentPage, setCurrentPage] = useState(0);
  const itemsPerPage = 10;
  const fetch = url + "?q=" + searchQuery + "&startIndex=" + (currentPage*itemsPerPage);

  const { data, isLoading, error } = useFetch(fetch);

  if (error) {
    return <p className="text-center mt-4">Houve um problema...</p>;
  }
  if (isLoading) {
    return <p className="text-center mt-4">carregando...</p>;
  }

  const { totalItems, items }: ISearch = data as any;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  console.log(data);

  const pages = paginate(currentPage, totalPages);
  console.log(pages); // [6, 7, 8, 9, 10]

  return (
    <>
      <div className="container mx-auto px-5 py-10">
        <div className="-m-4 flex flex-wrap">
          {items.map((item) => (
            <Card key={item.id} data={item}></Card>
          ))}
        </div>
      </div>
      <Pagination pages={pages} setCurrentPage={setCurrentPage}></Pagination>
    </>
  );
};

export default Results;
